# .prettierrc.toml

useTabs = true
tabWidth = 4
printWidth = 100
endOfLine = "lf"

# -- Not supported yet --
# trailingComma = "es5"
# embeddedLanguageFormatting = "auto"

# Example override
overrides = [
  { files = ["src/*.rs"], options = { printWidth = 80 } }
]